name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Clone Destination Repo
        uses: sudosubin/git-clone-action@v1.0.1
        with:
          repository: 'ctj12461/site-output'
          platform: 'github'
          path: 'dest'
      
      - run: cp -rf ./public/* ./dest/

      - name: Deploy
        uses: tech-thinker/push-to-repo@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.GIT_PAT_TOKEN }}
        with:
          source-directory: 'dest'
          destination-github-username: 'ctj12461'
          destination-repository-name: 'site-output'
          target-branch: main
